name: Vercel CD workflow

on:
  push:
    branches:
      - master
env:
  VERCEL_ORG_ID: ${{ sercrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ sercrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        run: vercel -t ${{ secrets.VERCEL_TOKEN }}
